// src/lib/components/QRCodeDisplay.svelte
<script lang="ts">
  import Check from 'lucide-svelte/icons/check';
  import Copy from 'lucide-svelte/icons/copy';
  import Download from 'lucide-svelte/icons/download';
  import X from 'lucide-svelte/icons/x';
  import * as QRCode from 'qrcode';
  import { onDestroy } from 'svelte';
  import { cn } from '$lib/utils';

  let {
    url,
    title,
    isOpen,
    onClose
  }: {
    url: string;
    title?: string;
    isOpen: boolean;
    onClose: () => void;
  } = $props();

  let copied = $state(false);
  let isVisible = $state(false);
  let shouldRender = $state(false);
  let qrDataUrl = $state('');
  let closeTimer: number | null = null;
  let copiedTimer: number | null = null;
  let entranceFrame: number | null = null;
  let visibilityFrame: number | null = null;

  const truncatedUrl = $derived(url.length > 40 ? `${url.substring(0, 37)}...` : url);

  $effect(() => {
    const targetUrl = url;
    void QRCode.toDataURL(targetUrl, {
      width: 200,
      margin: 0,
      errorCorrectionLevel: 'H',
      color: {
        dark: '#000000',
        light: '#ffffff'
      }
    }).then((dataUrl) => {
      if (targetUrl === url) {
        qrDataUrl = dataUrl;
      }
    });
  });

  $effect(() => {
    clearCloseAnimation();

    if (isOpen) {
      shouldRender = true;
      entranceFrame = requestAnimationFrame(() => {
        visibilityFrame = requestAnimationFrame(() => {
          isVisible = true;
          visibilityFrame = null;
        });
      });
    } else {
      isVisible = false;
      closeTimer = window.setTimeout(() => {
        shouldRender = false;
        closeTimer = null;
      }, 300);
    }
  });

  onDestroy(() => {
    clearCloseAnimation();
    if (copiedTimer !== null) {
      clearTimeout(copiedTimer);
    }
  });

  function clearCloseAnimation() {
    if (entranceFrame !== null) {
      cancelAnimationFrame(entranceFrame);
      entranceFrame = null;
    }
    if (visibilityFrame !== null) {
      cancelAnimationFrame(visibilityFrame);
      visibilityFrame = null;
    }
    if (closeTimer !== null) {
      clearTimeout(closeTimer);
      closeTimer = null;
    }
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(url);
    copied = true;
    if (copiedTimer !== null) {
      clearTimeout(copiedTimer);
    }
    copiedTimer = window.setTimeout(() => {
      copied = false;
      copiedTimer = null;
    }, 2000);
  }

  function handleDownload() {
    if (!qrDataUrl) return;
    const downloadLink = document.createElement('a');
    downloadLink.href = qrDataUrl;
    downloadLink.download = `${title || 'qrcode'}.png`;
    downloadLink.click();
  }

  function handleBackdropKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      onClose();
      return;
    }
    if ((event.key === 'Enter' || event.key === ' ') && event.target === event.currentTarget) {
      event.preventDefault();
      onClose();
    }
  }
</script>

{#if shouldRender}
  <div
    class={cn('modal-backdrop transition-all duration-300 ease-brutal', isVisible ? 'opacity-100' : 'opacity-0')}
    onclick={(event) => {
      if (event.target === event.currentTarget) {
        onClose();
      }
    }}
    onkeydown={handleBackdropKeydown}
    role="button"
    tabindex="0"
    aria-label="Close QR code modal"
  >
    <div
      class={cn(
        'modal transition-all duration-300 ease-brutal',
        isVisible ? 'translate-y-0 scale-100 opacity-100' : 'translate-y-4 scale-95 opacity-0'
      )}
    >
      <div class="modal-header flex items-center justify-between">
        <div>
          {#if title}
            <h3 class="text-h4 truncate pr-8 font-bold uppercase tracking-wider">{title}</h3>
          {/if}
          <p class="text-small text-brutal-black/60">Scan to open this flipbook</p>
        </div>
        <button type="button" onclick={onClose} class="btn-ghost btn-icon">
          <X class="h-5 w-5" />
        </button>
      </div>

      <div class="modal-body">
        <div class="qr-container mx-auto w-fit">
          {#if qrDataUrl}
            <img src={qrDataUrl} alt="QR code for {title || 'flipbook'}" width="200" height="200" />
          {/if}
        </div>

        <div class="mt-6 border-2 border-brutal-black bg-brutal-gray px-4 py-3">
          <p class="truncate text-center font-mono text-xs text-brutal-black" title={url}>
            {truncatedUrl}
          </p>
        </div>
      </div>

      <div class="modal-footer">
        <button
          type="button"
          onclick={handleCopy}
          class={cn('btn btn-sm flex-1', copied ? 'border-success bg-success text-brutal-white' : 'btn-outline')}
        >
          {#if copied}
            <Check class="h-4 w-4" />
            Copied!
          {:else}
            <Copy class="h-4 w-4" />
            Copy URL
          {/if}
        </button>

        <button type="button" onclick={handleDownload} class="btn btn-sm btn-primary flex-1">
          <Download class="h-4 w-4" />
          Download
        </button>
      </div>
    </div>
  </div>
{/if}

// src/components/QRCodeDisplay.tsx
"use client";

import { useState, useRef, useEffect } from "react";
import { QRCodeSVG } from "qrcode.react";
import { X, Copy, Download, Check } from "lucide-react";
import { cn } from "@/lib/utils";

interface QRCodeDisplayProps {
  url: string;
  title?: string;
  isOpen: boolean;
  onClose: () => void;
}

export function QRCodeDisplay({
  url,
  title,
  isOpen,
  onClose,
}: QRCodeDisplayProps) {
  const [copied, setCopied] = useState(false);
  const [isVisible, setIsVisible] = useState(false);
  const [shouldRender, setShouldRender] = useState(false);
  const qrRef = useRef<HTMLDivElement>(null);
  const entranceRafRef = useRef<number | null>(null);
  const visibilityRafRef = useRef<number | null>(null);
  const closeTimerRef = useRef<number | null>(null);
  const copiedTimerRef = useRef<number | null>(null);

  useEffect(() => {
    if (entranceRafRef.current !== null) {
      cancelAnimationFrame(entranceRafRef.current);
      entranceRafRef.current = null;
    }
    if (visibilityRafRef.current !== null) {
      cancelAnimationFrame(visibilityRafRef.current);
      visibilityRafRef.current = null;
    }
    if (closeTimerRef.current !== null) {
      clearTimeout(closeTimerRef.current);
      closeTimerRef.current = null;
    }

    if (isOpen) {
      setShouldRender(true);
      entranceRafRef.current = requestAnimationFrame(() => {
        visibilityRafRef.current = requestAnimationFrame(() => {
          setIsVisible(true);
          visibilityRafRef.current = null;
        });
      });
    } else {
      setIsVisible(false);
      closeTimerRef.current = window.setTimeout(() => {
        setShouldRender(false);
        closeTimerRef.current = null;
      }, 300);
    }

    return () => {
      if (entranceRafRef.current !== null) {
        cancelAnimationFrame(entranceRafRef.current);
        entranceRafRef.current = null;
      }
      if (visibilityRafRef.current !== null) {
        cancelAnimationFrame(visibilityRafRef.current);
        visibilityRafRef.current = null;
      }
      if (closeTimerRef.current !== null) {
        clearTimeout(closeTimerRef.current);
        closeTimerRef.current = null;
      }
    };
  }, [isOpen]);

  useEffect(() => {
    return () => {
      if (copiedTimerRef.current !== null) {
        clearTimeout(copiedTimerRef.current);
        copiedTimerRef.current = null;
      }
    };
  }, []);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(url);
    setCopied(true);
    if (copiedTimerRef.current !== null) {
      clearTimeout(copiedTimerRef.current);
    }
    copiedTimerRef.current = window.setTimeout(() => {
      setCopied(false);
      copiedTimerRef.current = null;
    }, 2000);
  };

  const handleDownload = () => {
    const svg = qrRef.current?.querySelector("svg");
    if (!svg) return;

    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const svgData = new XMLSerializer().serializeToString(svg);
    const img = new Image();
    const svgBlob = new Blob([svgData], {
      type: "image/svg+xml;charset=utf-8",
    });
    const svgUrl = URL.createObjectURL(svgBlob);

    img.onload = () => {
      canvas.width = 400;
      canvas.height = 400;
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, 400, 400);
      ctx.drawImage(img, 0, 0, 400, 400);
      URL.revokeObjectURL(svgUrl);

      const pngUrl = canvas.toDataURL("image/png");
      const downloadLink = document.createElement("a");
      downloadLink.href = pngUrl;
      downloadLink.download = `${title || "qrcode"}.png`;
      downloadLink.click();
    };

    img.src = svgUrl;
  };

  const truncatedUrl =
    url.length > 40 ? `${url.substring(0, 37)}...` : url;

  if (!shouldRender) return null;

  return (
    <div
      className={cn(
        "modal-backdrop",
        "transition-all duration-300 ease-brutal",
        isVisible ? "opacity-100" : "opacity-0"
      )}
      onClick={(event) => {
        if (event.target === event.currentTarget) {
          onClose();
        }
      }}
      onKeyDown={(event) => {
        if (event.key === "Escape") {
          onClose();
          return;
        }
        if (
          (event.key === "Enter" || event.key === " ") &&
          event.target === event.currentTarget
        ) {
          event.preventDefault();
          onClose();
        }
      }}
      role="button"
      tabIndex={0}
      aria-label="Close QR code modal"
    >
      <div
        className={cn(
          "modal",
          "transition-all duration-300 ease-brutal",
          isVisible
            ? "opacity-100 scale-100 translate-y-0"
            : "opacity-0 scale-95 translate-y-4"
        )}
      >
        <div className="modal-header flex items-center justify-between">
          <div>
            {title && (
              <h3 className="text-h4 font-bold uppercase tracking-wider truncate pr-8">
                {title}
              </h3>
            )}
            <p className="text-small text-brutal-black/60">
              Scan to open this flipbook
            </p>
          </div>
          <button
            onClick={onClose}
            className="btn-ghost btn-icon"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="modal-body">
          <div
            ref={qrRef}
            className="qr-container mx-auto w-fit"
          >
            <QRCodeSVG
              value={url}
              size={200}
              level="H"
              includeMargin={false}
              bgColor="#ffffff"
              fgColor="#000000"
            />
          </div>

          <div className="mt-6 px-4 py-3 bg-brutal-gray border-2 border-brutal-black">
            <p
              className="text-xs font-mono text-center text-brutal-black truncate"
              title={url}
            >
              {truncatedUrl}
            </p>
          </div>
        </div>

        <div className="modal-footer">
          <button
            onClick={handleCopy}
            className={cn(
              "btn btn-sm flex-1",
              copied
                ? "bg-success text-brutal-white border-success"
                : "btn-outline"
            )}
          >
            {copied ? (
              <>
                <Check className="w-4 h-4" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy URL
              </>
            )}
          </button>

          <button
            onClick={handleDownload}
            className="btn btn-sm btn-primary flex-1"
          >
            <Download className="w-4 h-4" />
            Download
          </button>
        </div>
      </div>
    </div>
  );
}
